<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8232" started-at="2014-08-05T20:00:52Z" finished-at="2014-08-05T20:01:01Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8232" started-at="2014-08-05T20:00:52Z" finished-at="2014-08-05T20:01:01Z">
      <class name="sb.wd.test.NavigateAllTabsTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:sb.wd.test.NavigateAllTabsTest@40133da0]" name="setUp" is-config="true" duration-ms="5832" started-at="2014-08-05T14:00:53Z" finished-at="2014-08-05T14:00:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testNavigateAllTabs(java.lang.String, java.lang.String)[pri:0, instance:sb.wd.test.NavigateAllTabsTest@40133da0]" name="testNavigateAllTabs" duration-ms="1511" started-at="2014-08-05T14:00:59Z" data-provider="Authentication" finished-at="2014-08-05T14:01:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
null, null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
null, null
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
	at sb.wd.test.NavigateAllTabsTest.testNavigateAllTabs(NavigateAllTabsTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNavigateAllTabs -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:sb.wd.test.NavigateAllTabsTest@40133da0]" name="tearDown" is-config="true" duration-ms="195" started-at="2014-08-05T14:01:00Z" finished-at="2014-08-05T14:01:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- sb.wd.test.NavigateAllTabsTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
